---
extends:
  - airbnb-base
  - plugin:import/warnings

env:
  browser: 1

plugins:
  - dependencies

settings:
  import/resolver: webpack

rules:
  no-console: 0

parser: babel-eslint

globals:
  inject: false
