api:
  websocketUrl: 'wss://turg-svc.herokuapp.com/v1/ws/'
  mapping:
    x: x
    y: z
    z: y

world:
  size:
    side: 5000
    height: 100

performance:
  initialRange: 5000
  meshBatchSize: 2000
